### PR TITLE
Console.WriteLine prints output in the notebook now. Fixes #4.

### LINKED ISSUE #4: Console.WriteLine does not print output in the notebook
I think you can register for Console Printouts via Trace.Listener.Add.
Here is a snipped that use to display a virtual console:

```
    #region  HelperClass TConsoleTraceListener
    public class TConsoleTraceListener : TraceListener
    {
        #region Variables
        TConsole _parent;
        #endregion

        #region Constructor
        public TConsoleTraceListener (TConsole parent)
        {
            _parent = parent;
            //Debug.Listeners.Clear ();
            //Debug.Listeners.Add (this);
            //Trace.Listeners.Clear ();
            Trace.Listeners.Add (this);
        }
        #endregion

        #region TraceListener Overrides
        override public void Write(string message) 
        {
            try
            {
                _parent.WriteLine (message);
            }
            catch (Exception ex)
            {
                ;
                Console.Write ("Ex="+ex.Message );
            }
        }
        override public void WriteLine(string message) 
        {     
            try
            {
                _parent.WriteLine (message);
            }
            catch (Exception ex)
            {
                ;
                Console.Write ("Ex="+ex.Message );
            }
        }
        #endregion
    }
    #endregion
```

### PR DESCRIPTION
**Pull request by gabrielgt**

### CODE REVIEW

**Comment by zabirauf** [comment]
Thanks a lot for the fix. I will take a look at the changes and merge if have no comments

**Comment by thomasjm** [comment]
This broke the build for me on Linux. I think it's a case-sensitivity issue; this PR added the line `<Compile Include="ScriptEngine\IOPubConsole.cs" />` to the `.sln` file but the actual source file is called `IoPubConsole.cs`.

**Comment by thomasjm** [comment]
(Oh this is the same reason the Travis build failed :P)

**Comment by zabirauf** [comment]
@thomasjm  Ohh, let me take a look at it. If you already have fix for it, do send out a PR :). Thanks!

**Comment by thomasjm** [comment]
I don't have a PR, I just downgraded my dependency so it doesn't hit this. I believe all that is needed is to rename `IoPubConsole.cs` to `IOPubConsole.cs`.

**Pull request merged**
