### PR TITLE
these changes made the notebook working with jupyter/ipython 4.0

### PR DESCRIPTION
**Pull request by denfromufa**

### CODE REVIEW

**Comment by denfromufa** [comment]
@zabirauf travis-ci is requesting config file, weird, this does not seem to be happening in @minrk pull request

**Comment by zabirauf** [comment]
Yep, the .travis.yml is still in develop branch and not in master and when i go over to travis seems like it hasn't picked any branches yet. I am looking into it and will merge with master and then merge your pull request.

**Comment by zabirauf** [comment]
It didn't happen with @minrk pull request because i just activated travis for the repository few minutes before your pull request hence travis only picked your PR

**Comment by zabirauf** [comment]
Thanks a lot @denfromufa for the fix.

**Comment by awb99** [comment]
@denfromufa can you have a look at the docker image that I made.. I think I have to sort outa minor issue regarding to jupyter 4 protocol.

**Comment by denfromufa** [comment]
Can I run this docker on windows, I do not have a good Linux at hand?

Does jupyter has to be inside docker container or it is possible to have it
outside?

**Comment by awb99** [comment]
Years ago, Dockers only did run on host=linux and guest=linux. Reading this article made me think that it works now on windows also: https://docs.docker.com/windows/step_one/

My main issue with icsharp is, that I cannot just install it in a few seconds on a windows/linux computer, and just work with it. For this reason, I decied that a docker image might help.
With 1 line command one could build a new docker image (which would build a complete linux system, including jupyter, including mono, including icsharp, and including the integration between them).

With one additional line you start docker, and you access jupyter via webbrowser. AND you can have all the workbooks in a folder on the host; so the docker virtual machine can be simply discarded when no longer needed.

So to answer your question: my idea is to run jupyter inside the container, but you access it via a webbrowser from outside the container.

**Pull request merged**
