### PR TITLE
add csharp folder for Jupyter Kernel

### PR DESCRIPTION
**Pull request by gwenzek**
I added a 'kernel.json' file in order to facilitate the installation with Jupyter.
I described the installation in the [wiki](https://github.com/zabirauf/icsharp/wiki/Installation).

### CODE REVIEW

**Comment by gwenzek** [comment]
The build is failing, but I didn't modify any code, so I don't think I'm responsible for this...
Please, could someone look into it ?

**Comment by denfromufa** [comment]
@gwenzek @zabirauf looks like nuget is not found during build process:

```
PackageAssemblyResolverTests.cs(8,7): error CS0246: The type or namespace name `NuGet' could not be found. Are you missing an assembly reference?
			Task "Csc" execution -- FAILED
```

so most likely something has changed with c#/mono setup in travis ci

**Comment by denfromufa** [comment]
but generally +1 on this effort for installing kernelspec

**Comment by zabirauf** [comment]
@gwenzek where will this kernelspec be used in the installation phase?

**Comment by gwenzek** [comment]
As described in the [wiki](https://github.com/zabirauf/icsharp/wiki/Installation) (linked in my original post) this kernelspec is copied by Jupyter in its directory with the command `jupyter kernelspec install` 

Before that the kernelspec should be modified to point to the installation path of icsharp. Maybe I could add a script that does it based on the cuurent path.

**Comment by awb99** [comment]
Gents! My docker image does install the kernelspec file by COPYING the kernel.json file across. For some reason the jupyter kernelspec install command did not work on my dockers image

**Comment by zabirauf** [comment]
@gwenzek Can you instead change the name of the folder to `kernel-spec` and send the pull request. Make sure to rebase it so that its only one commit.

Following the folder structure of [iFsharp](https://github.com/fsprojects/IfSharp/tree/master/kernel-spec)

**Comment by gwenzek** [comment]
@zabirauf done :-)

**Comment by zabirauf** [comment]
@gwenzek Thanks :+1:

**Comment by kiln1452** [comment]
Hi there,

I have cloned the repository, but the folder 'Engine' is empty.  This means that files such as ScriptCs.csproj are missing (and a whole list of others).  It's the same issue when I download the Zip.  Any ideas?

i.e., The Visual Studio solution is trying the find the following path... (everything up to 'Engine' is there)

Jupyter_d\icsharp-master\icsharp-master\Engine\src\ScriptCs\ScriptCs.csproj

**Comment by denfromufa** [comment]
ScriptCs should be downloaded during build process as nuget package, isn't
it? It is external dependency, hence not bundled.

BTW, I made a pip installable clrmagic project to have C# magic cells in
IPython kernel:

https://pypi.python.org/pypi/clrmagic/

**Comment by zabirauf** [comment]
@kiln1452 The ScriptCs is a git submodule. You can use the following command to clone which will also pull in the Engine

```
git clone --recursive https://github.com/zabirauf/icsharp.git
```

**Pull request merged**
